
services:
  postgres:
    image: postgres:16
    container_name: certifications-postgres
    environment:
      POSTGRES_DB: certifications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
